version: '3.8'
services:
  db: # server name
      image: mariadb:10.8.3
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3307:3306
      volumes:
            - ./var/database:/var/lib/mysql:delegated
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
